### ISSUE TITLE
conda crash on appveyor build

### ISSUE THREAD

**Issue by skoudoro** [conda-forge/dipy-feedstock#17]
On PR #16, It seems that Conda installation crash as you can see [here](https://ci.appveyor.com/project/conda-forge/dipy-feedstock/build/1.0.39/job/g13du2o94wrmatxa)

Did I do something wrong @arokem and  @conda-forge/core team? 

Below, the error:
```
Build started
git clone -q https://github.com/conda-forge/dipy-feedstock.git C:\projects\dipy-feedstock
git fetch -q origin +refs/pull/16/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py', 'ff_ci_pr_build.py')"
ff_ci_pr_build -v --ci "appveyor" "%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%" "%APPVEYOR_BUILD_NUMBER%" "%APPVEYOR_PULL_REQUEST_NUMBER%"
Checking to see if this PR build is outdated.
del ff_ci_pr_build.py
rmdir C:\cygwin /s /q
call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
Activating environment "C:\Miniconda"...
conda update --yes --quiet conda
Fetching package metadata: ....
.Solving package specifications: .
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:
    https://github.com/conda/conda/issues
Include the output of the command 'conda info' in your report.
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Miniconda\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Miniconda\lib\site-packages\conda\cli\main_update.py", line 64, in execute
    install.install(args, parser, 'update')
  File "C:\Miniconda\lib\site-packages\conda\cli\install.py", line 334, in install
    update_deps=args.update_deps)
  File "C:\Miniconda\lib\site-packages\conda\plan.py", line 413, in install_actions
    pkgs = r.install(specs, [d + '.tar.bz2' for d in linked], update_deps=update_deps)
  File "C:\Miniconda\lib\site-packages\conda\resolve.py", line 875, in install
    pkgs = self.solve(specs, len0=len0, returnall=returnall)
  File "C:\Miniconda\lib\site-packages\conda\resolve.py", line 909, in solve
    dists, new_specs = self.get_dists(specs)
  File "C:\Miniconda\lib\site-packages\conda\resolve.py", line 399, in get_dists
    specs, removes, optional, features = self.verify_specs(specs)
  File "C:\Miniconda\lib\site-packages\conda\resolve.py", line 391, in verify_specs
    bad_deps.extend(self.invalid_chains(ms, filter))
  File "C:\Miniconda\lib\site-packages\conda\resolve.py", line 359, in invalid_chains
    return chains_(spec)
  File "C:\Miniconda\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Miniconda\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Miniconda\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Miniconda\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Miniconda\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Miniconda\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Miniconda\lib\site-pa
```

**Comment by Garyfallidis** [comment]
@isuruf can you have a look at this issue? We have delayed the release announcement for a month now.
It seems last time you really help us with the VS issue. But now the error seems related to anaconda itself.
Thanks in advance. Also, if you are not familiar with the issue perhaps suggest someone else from the Anaconda team?

**Comment by isuruf** [comment]
I think the conda issue was fixed in the latest appveyor update.

**Comment by skoudoro** [comment]
Thanks @isuruf ! Indeed, the issue seems to be fixed and everything is going well now!
